// templates/vue-vite/overlays/tailwind/js/src/features/increment-counter/ui/IncrementCounterButton.vue
<script setup>
const props = defineProps({
  counter: {
    type: Object,
    required: true,
  },
});

const emit = defineEmits(["increment"]);
</script>

<template>
  <button
    class="py-2 px-6 text-base cursor-pointer rounded-md"
    @click="emit('increment', props.counter.id)"
  >
    카운트: {{ props.counter.value }}
  </button>
</template>

// templates/react-vite/overlays/tailwind/src/features/increment-counter/ui/IncrementCounterButton.jsx
/**
 * @param {{ counter: import("@/entities/counter").CounterDto, onIncrement: (id: string) => void }} props
 */
export function IncrementCounterButton({ counter, onIncrement }) {
  return (
    <button
      className="py-2 px-6 text-base cursor-pointer rounded-md"
      onClick={() => onIncrement(counter.id)}
    >
      카운트: {counter.value}
    </button>
  );
}
