// templates/react-vite/overlays/store-zustand/src/features/counter-store/ui/CounterWithStore.tsx
import { useCounterStore } from "../model/store";

export function CounterWithStore() {
  const count = useCounterStore((s) => s.count);
  const increment = useCounterStore((s) => s.increment);
  const decrement = useCounterStore((s) => s.decrement);
  const reset = useCounterStore((s) => s.reset);

  return (
    <div style={{ display: "flex", flexDirection: "column", alignItems: "center", gap: "1rem" }}>
      <p style={{ fontSize: "2rem", fontWeight: 700, margin: 0 }}>{count}</p>
      <div style={{ display: "flex", gap: "0.5rem" }}>
        <button onClick={decrement} style={{ padding: "0.4rem 1rem", cursor: "pointer" }}>
          -
        </button>
        <button onClick={increment} style={{ padding: "0.4rem 1rem", cursor: "pointer" }}>
          +
        </button>
        <button onClick={reset} style={{ padding: "0.4rem 1rem", cursor: "pointer" }}>
          초기화
        </button>
      </div>
    </div>
  );
}

// templates/vue-vite/overlays/store-pinia/src/features/counter-store/ui/CounterWithStore.vue
<script setup lang="ts">
import { storeToRefs } from "pinia";
import { useCounterStore } from "../model/store";

const counterStore = useCounterStore();
const { count } = storeToRefs(counterStore);
</script>

<template>
  <div class="counter">
    <p class="count">{{ count }}</p>
    <div class="actions">
      <button @click="counterStore.decrement">-</button>
      <button @click="counterStore.increment">+</button>
      <button @click="counterStore.reset">초기화</button>
    </div>
  </div>
</template>

<style scoped>
.counter {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 1rem;
}

.count {
  font-size: 2rem;
  font-weight: 700;
  margin: 0;
}

.actions {
  display: flex;
  gap: 0.5rem;
}

.actions button {
  padding: 0.4rem 1rem;
  cursor: pointer;
}
</style>
