// templates/vue-vite/base-js/src/views/home/ui/HomePage.vue
<script setup>
import { ref } from "vue";
import { CounterStatus } from "@/entities/counter";
import { IncrementCounterButton } from "@/features/increment-counter";

const counter = ref({
  id: "1",
  value: 0,
  status: CounterStatus.ACTIVE,
});

const handleIncrement = (id) => {
  if (id !== counter.value.id) return;
  counter.value = { ...counter.value, value: counter.value.value + 1 };
};
</script>

<template>
  <div class="home">
    <h1>__PROJECT_NAME__</h1>
    <p>FSD(Feature-Sliced Design) 기반 프로젝트입니다.</p>
    <IncrementCounterButton :counter="counter" @increment="handleIncrement" />
  </div>
</template>

<style scoped>
.home {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  min-height: 100vh;
  gap: 1rem;
}

h1 {
  font-size: 2.5rem;
  font-weight: 700;
  margin: 0;
}

p {
  font-size: 1rem;
  color: rgba(255, 255, 255, 0.6);
  margin: 0;
}
</style>

// templates/react-vite/overlays/tailwind/src/views/home/ui/HomePage.jsx
import { useState } from "react";
import { CounterStatus } from "@/entities/counter";
import { IncrementCounterButton } from "@/features/increment-counter";

export function HomePage() {
  const [counter, setCounter] = useState({
    id: "1",
    value: 0,
    status: CounterStatus.ACTIVE,
  });

  const handleIncrement = (id) => {
    if (id !== counter.id) return;
    setCounter((prev) => ({ ...prev, value: prev.value + 1 }));
  };

  return (
    <div className="flex flex-col items-center justify-center min-h-screen gap-4 text-center p-8">
      <h1 className="text-4xl font-bold">__PROJECT_NAME__</h1>
      <p className="text-base text-white/60">FSD(Feature-Sliced Design) 기반 프로젝트입니다.</p>
      <IncrementCounterButton counter={counter} onIncrement={handleIncrement} />
    </div>
  );
}
